#!/usr/bin/env python3
"""Regenerate wiki/index.md from page frontmatter.

The index is a DERIVED artifact — never hand-edited, gitignored — so it can't drift. Pages
live in one subdirectory per group under wiki/. The set of groups is NOT fixed and is not
predefined here: any subdirectory is a group, discovered at runtime, so the keeper can create
whatever groups the domain needs. index.md, overview.md and synthesis.md stay at the wiki/
root; log.md sits at the WIKI root, one level above wiki/. See references/directory-layout.md
and references/page-conventions.md.

Usage:
    build_index.py <wiki-root>        # explicit wiki root
    build_index.py --auto             # resolve from cwd; exit 0 silently if not in a wiki

Dependencies: standard library only.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from _frontmatter import atomic_write, find_wiki_root_auto, parse_frontmatter, read_text, validate_wiki_root


def groups(wiki_dir: Path) -> list[Path]:
    """All page-group subdirectories under wiki/, discovered from the filesystem, sorted."""
    dirs = [d for d in wiki_dir.iterdir() if d.is_dir()] if wiki_dir.exists() else []
    return sorted(dirs, key=lambda d: d.name)


def build_index(wiki_root: Path) -> str:
    wiki_dir = wiki_root / "wiki"
    lines = ["# Index", "", "<!-- GENERATED by build_index.py — do not edit by hand. -->", ""]
    for group in groups(wiki_dir):
        pages = sorted(group.glob("*.md"))
        if not pages:
            continue  # skip empty groups (e.g. freshly initialized)
        lines.append(f"## {group.name.replace('-', ' ').title()}")
        lines.append("")
        for page in pages:
            fm = parse_frontmatter(read_text(page))
            # Collapse any whitespace (a JSON-decoded multiline value can carry a newline) so one
            # page is always one list item — a stray newline would otherwise break the index.
            title = " ".join((fm.get("title") or page.stem).split())
            summary = " ".join(fm.get("summary", "").split())
            suffix = f" — {summary}" if summary else ""
            lines.append(f"- [{title}]({group.name}/{page.stem}.md){suffix}")
        lines.append("")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate wiki/index.md from page frontmatter.")
    parser.add_argument("wiki_root", nargs="?", help="wiki root (dir containing SCHEMA.md)")
    parser.add_argument("--auto", action="store_true", help="resolve wiki root from cwd; no-op if none")
    args = parser.parse_args(argv)

    if args.auto:
        root = find_wiki_root_auto(Path.cwd())
        if root is None:
            return 0  # not in a wiki — silent no-op (used by the Stop hook)
    elif args.wiki_root:
        root = Path(args.wiki_root).resolve()
        problem = validate_wiki_root(root)
        if problem:
            print(problem, file=sys.stderr)
            return 2
    else:
        parser.error("provide a wiki root or --auto")

    (root / "wiki").mkdir(exist_ok=True)
    atomic_write(root / "wiki" / "index.md", build_index(root) + "\n")

    if not args.auto:  # the Stop hook runs every turn and stays quiet; a manual run reports
        filled = [g for g in groups(root / "wiki") if any(g.glob("*.md"))]
        pages = sum(len(list(g.glob("*.md"))) for g in filled)
        print(f"wrote wiki/index.md - {pages} pages in {len(filled)} groups")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
